title_name = "Saints Row" # TU1
title_id = "545107D1" # TQ-2001
#hash = "" # default.xex
#media_id = "24367742"

[[patch]]
    name = "Enable Debug Console"
    desc = "Requires keyboard_passthru to be changed from false to true in the Xenia config."
    author = "emoose"
    is_enabled = false

    [[patch.be32]]
        address = 0x8265F694
        value = 0x48000AA4
    [[patch.be32]]
        address = 0x82660134
        value = 0x480B8EF9
    [[patch.be32]]
        address = 0x82660268
        value = 0x480B8E14
    [[patch.be8]]
        address = 0x835F4C3E
        value = 0x01
		
[[patch]]
    name = "Enable r_ugly_mode"
    desc = "Enables r_ugly_mode - more fps but worse graphics. might be unstable."
    author = "Hasster"
    is_enabled = false

    [[patch.be16]]
        address = 0x835F2164
        value = 0x0001
    [[patch.be8]]
        address = 0x827F7A5C
        value = 0x00
    [[patch.be8]]
        address = 0x827F7A5D
        value = 0x00
    [[patch.be8]]
        address = 0x827F7A5E
        value = 0x00
    [[patch.be8]]
        address = 0x827F7A5F
        value = 0x00
